.gitignore, CHANGELOG.md, README.md, cli/README.md, cli/src/main.rs, cli/src/path.rs, lib/examples/basic.rs, lib/src/atoms.rs, lib/src/client.rs, lib/src/collections.rs, lib/src/db.rs, lib/src/lib.rs, lib/src/parse.rs, lib/src/plugins/path.rs, lib/src/plugins/versioning.rs, lib/src/resources.rs, lib/src/serialize.rs, lib/src/store.rs, lib/src/storelike.rs, lib/src/test_utils.rs, lib/src/validate.rs, server/example_requests.http, server/src/content_types.rs, server/src/handlers/resource.rs, server/src/handlers/tpf.rs
The first store was string based, and the Resource model was String based too. This, however, led to incorrect datatypes. I made the store stricter by storing Enum Values. This PR cleans up the last remnants of this older data model.
But I'm not 100% sure that the string based atoms have no value / no reason to exist. That's why this isn't merged yet.
=> Remove String Atom, only use RichAtom

CHANGELOG.md, server/Cargo.toml, server/src/appstate.rs, server/src/bin.rs, server/src/lib.rs, server/src/serve.rs
Makes all process management features opt-in. Makes the binary smaller, and has a more unix-like default behaviour.
PR Checklist:
=> #324 #334 optional process management

CHANGELOG.md, lib/src/db.rs, lib/src/db/migrations.rs, server/e2e_tests/e2e.spec.ts, server/src/bin.rs
Enables automated migrations for making schema changes in the sled store
PR Checklist:
=> Migrations in Sled KV store

lib/src/commit.rs
e449e83cb67ca4347627d1e5953145d22e8bfa66 has (accidentally?) removed handling of `remove` field on commits, so removing properties no longer works.
This PR restores it.
Tested it locally with my client code.
PR Checklist:
=> fix: handle removes in commit

lib/src/commit.rs
Run rustfmt.
I also took a look at failing e2e tests—it seems that they are failing because of changes to atomicdata.dev: changing title from `atomicdata.dev` to `Atomic Data ` and removing `demo invite` from the sidebar.
PR Checklist:
=> fix: run rustfmt

server/src/handlers/search.rs
All property-scoped searches failed with `Error parsing query Syntax Error`.
This happened because the following code
```rust
let full_query = if let Some(prop) = &params.property {
format!("property:{:?} AND {}", prop, &q)
} else {
q
};
```
would produce a query like: `https://atomicdata.dev/properties/name:hello`
and this likely fails to parse because of multiple `:` in a string.
You can test this with the following link:
https://atomicdata.dev/search?q=hello&property=https%3A%2F%2Fatomicdata.dev%2Fproperties%2Fname
I am not sure how this was supposed to work, but I intuited my way to add property:"property-name" to query and AND-combine that with user's query.
```rust
format!("property:{:?} AND {}", prop, &q)
```
I could probably scope user's query to value:
```rust …
```
=> fix property-scoped search

server/src/handlers/commit.rs
1c25aed4a769d7760780f59626872b6fb752d44a disabled it for library, but not the server.
PR Checklist:
=> fix: disable previous commit validation for real

CHANGELOG.md, lib/src/hierarchy.rs
=> #521 Give server default agent sudo rights

CHANGELOG.md, server/src/helpers.rs
=> Cookie authentication bug #525

CHANGELOG.md, README.md, server/STATUS.md
=> Create STATUS.md, give insight in feature stability

CHANGELOG.md, CONTRIBUTE.md, Cargo.lock, server/Cargo.toml, server/src/https_init.rs
=> - Replace `acme_lib` with `instant-acme`, drop OpenSSL dependency #192

CHANGELOG.md, lib/src/db.rs, lib/src/db/prop_val_sub_index.rs, lib/src/db/test.rs, lib/src/db/val_prop_sub_index.rs, lib/src/parse.rs, lib/src/populate.rs, lib/src/storelike.rs, server/e2e_tests/e2e-generated.spec.ts, server/src/appstate.rs, server/src/serve.rs, server/src/tests.rs
=> Rebuilding indexes done on separate thread, only once #616 #615

browser/package.json
This should help with some of the tools we are trying to use to package this for Summer of Nix as part of https://github.com/ngi-nix/ngipkgs/issues/15
One unclear thing is that https://github.com/atomicdata-dev/atomic-server/releases/tag/v0.34.3 is tagged in git as `0.34.3` but the title of the release is `0.34.5`. Not sure if that is a typo (the patch version is different), but we went with the git tag.
=> Add version to package.json

browser/data-browser/src/components/Popover.tsx, browser/data-browser/src/components/TableEditor/Cell.tsx, browser/data-browser/src/components/TableEditor/TableEditor.tsx, browser/data-browser/src/components/TableEditor/TableEditorContext.tsx, browser/data-browser/src/components/TableEditor/hooks/useTableEditorKeyboardNavigation.tsx, browser/data-browser/src/components/forms/AtomicSelectInput.tsx, browser/data-browser/src/views/OntologyPage/OntologyPage.tsx, browser/data-browser/src/views/OntologyPage/Property/PropertyLineWrite.tsx, browser/data-browser/src/views/TablePage/EditorCells/ResourceArrayCell.tsx, browser/data-browser/src/views/TablePage/PropertyForm/Tag.tsx, browser/data-browser/src/views/TablePage/TableCell.tsx, browser/pnpm-lock.yaml
=>  #638 Table Fixes and features

browser/data-browser/src/components/TableEditor/TableHeader.tsx, browser/data-browser/src/components/TableEditor/TableHeading.tsx, browser/data-browser/src/hooks/useResizable.ts, browser/data-browser/src/views/TablePage/TableHeading.tsx
=> #765 Better table column header

browser/CHANGELOG.md, browser/data-browser/src/components/Card.tsx, browser/data-browser/src/components/Navigation.tsx, browser/data-browser/src/components/PropVal.tsx, browser/data-browser/src/components/Searchbar.tsx, browser/data-browser/src/components/ValueComp.tsx, browser/data-browser/src/components/datatypes/Markdown.tsx, browser/data-browser/src/components/forms/ValueForm.tsx, browser/data-browser/src/routes/SearchRoute.tsx, browser/data-browser/src/views/Card/BookmarkCard.tsx, browser/data-browser/src/views/Card/CollectionCard.tsx, browser/data-browser/src/views/Card/ElementCard.tsx, browser/data-browser/src/views/Card/ResourceCard.tsx, browser/data-browser/src/views/Card/ResourceCardTitle.tsx, browser/data-browser/src/views/File/FileCard.tsx, browser/data-browser/src/views/File/FilePreview.tsx, browser/data-browser/src/views/File/isTextFile.ts
=> #770 better search result styling

browser/CHANGELOG.md, browser/data-browser/src/components/TableEditor/hooks/usePasteCommand.ts
=>  #771 Don't use custom paste logic when user is typing

browser/CHANGELOG.md, browser/lib/src/store.test.ts, browser/lib/src/store.ts, docs/src/js.md
=>  #798 Streamline Resource Creation API

browser/CHANGELOG.md, browser/data-browser/src/components/forms/SearchBox/SearchBox.tsx, browser/data-browser/src/helpers/navigation.tsx
=>  #810 Add goto button to searchbox

README.md
~~PR Checklist:~~
~~- [ ] Link to related issues: #number~~
~~- [ ] Add changelog entry linking to issue, describe API changes~~
~~- [ ] Add tests (optional)~~
~~- [ ] (If new feature) add to description / readme~~
there's no linking api change, test or issue since this is just a dead link fix. 
the link to install instructions from the main README is broken (see 'dead link' below). it points to `atomicserver/intro.html`. 
<details><summary>dead link</summary>
</details>
- I updated the url to point to the install page `atomicserver/installation`
- I opted to follow the md link style as the badges, putting the hyperlink at the footer of the doc 
<details><summary>manual test</summary>
</details>
=> fix(docs): correct dead link to install docs

browser/CHANGELOG.md, browser/data-browser/src/components/forms/InputDate.tsx, browser/data-browser/src/components/forms/InputSwitcher.tsx, browser/data-browser/src/components/forms/InputTimestamp.tsx, browser/data-browser/src/components/forms/hooks/useDateTimeInput.ts, browser/data-browser/src/views/TablePage/EditorCells/DateTimeCell.tsx, browser/pnpm-lock.yaml
=> #841-datetime-picker

browser/CHANGELOG.md, browser/data-browser/src/components/forms/InputResourceArray.tsx, browser/data-browser/src/components/forms/ResourceSelector/ResourceSelector.tsx, browser/data-browser/src/components/forms/SearchBox/SearchBox.tsx, browser/data-browser/src/components/forms/SearchBox/SearchBoxButton.tsx, browser/data-browser/src/components/forms/SearchBox/SearchBoxWindow.tsx
=> #850 Add d&d to resource array input

browser/data-browser/src/views/OntologyPage/PropertyDatatypePicker.tsx
Classtype is only a valid piece of state when datatype is resource or resource array. Setting the datatype to something else now clears the classtype, like it has been clearing the allows-only list.
Also changed `urls` -> `core` because deprecated.
=> Clear classtype when setting datatype, if datatype is not resource or resource array

lib/src/db.rs
Without this, any data we have added is only going to be properly persisted if sled happened to complete one of its automatic syncs after the addition (this happens every 500ms by default, [per their README](https://github.com/spacejam/sled?tab=readme-ov-file#expectations-gotchas-advice)).
When running a server, this is usually not an issue, but a command like `atomic-server import` may complete quite quickly, making us lose some or even all of our data to be imported. (In fact, this is how I found the issue: I was wondering why the import command seemed to have no effect.)
=> Give Db a destructor invoking self.db.flush()

Earthfile, browser/CHANGELOG.md, browser/data-browser/src/components/Main.tsx, browser/data-browser/src/hooks/useAddToOntology.ts, browser/data-browser/src/views/OntologyPage/NewClassButton.tsx, browser/data-browser/src/views/OntologyPage/OntologyContext.tsx, browser/data-browser/src/views/OntologyPage/OntologyPage.tsx, browser/data-browser/src/views/OntologyPage/newClass.ts, browser/data-browser/src/views/OntologyPage/sortSubjectList.ts, browser/data-browser/src/views/TablePage/PropertyForm/NewPropertyDialog.tsx, browser/data-browser/src/views/TablePage/TablePage.tsx, browser/e2e/tests/ontology.spec.ts
=>  #919 Sort classes in Ontology viewer

lib/README.md
Navigating links README to `atomic-cli` and `atomic-server`.
closes #
=> docs: intended README links

CHANGELOG.md, lib/benches/benchmarks.rs, lib/src/authentication.rs, lib/src/commit.rs, lib/src/db.rs, lib/src/db/migrations.rs, lib/src/db/prop_val_sub_index.rs, lib/src/db/query_index.rs, lib/src/db/test.rs, lib/src/db/trees.rs, lib/src/db/val_prop_sub_index.rs, lib/src/parse.rs, lib/src/plugins/chatroom.rs, lib/src/plugins/versioning.rs, lib/src/resources.rs, lib/src/store.rs, lib/src/storelike.rs, lib/src/utils.rs, server/build.rs, server/src/commit_monitor.rs, server/src/handlers/commit.rs, server/src/serve.rs
=> Move `commit::apply_opts` to `store::apply_commit` #297
