atomicdata-dev/atomic-server

lib/examples/compare_ring.rs
lib/src/agents.rs
lib/src/commit.rs
lib/src/errors.rs
lib/src/storelike.rs
server/src/appstate.rs

Change commit serialization no pkcs8 #98

---

cli/src/main.rs
lib/defaults/default_store.json
lib/src/commit.rs
lib/src/db.rs
lib/src/plugins/versioning.rs
lib/src/populate.rs
lib/src/resources.rs
lib/src/serialize.rs
lib/src/storelike.rs
lib/src/urls.rs
server/README.md
server/src/appstate.rs
server/src/config.rs
server/src/handlers/commit.rs
server/src/main.rs

#14 value index

---

CHANGELOG.md
lib/src/populate.rs
lib/src/resources.rs
lib/src/schema.rs
lib/src/urls.rs
server/README.md
server/benchmark.yml

#206 allows only enum

---

CHANGELOG.md
lib/defaults/default_store.json
lib/src/commit.rs
lib/src/plugins/invite.rs
lib/src/plugins/versioning.rs
lib/src/urls.rs

#182 invite checks

---

.github/workflows/tauri-publish.yml
CHANGELOG.md
server/README.md

#221 tauri ci

---

.github/workflows/main.yml
Cargo.toml
src-tauri/Cargo.lock

#230 don't include tantivy in main src

---

lib/defaults/default_store.json
lib/src/populate.rs

#219 add default store structure

---

CHANGELOG.md
lib/src/populate.rs
lib/src/resources.rs
server/src/appstate.rs

#243 append rights to drive in initialize

---

CHANGELOG.md
lib/src/collections.rs
lib/src/db.rs
lib/src/serialize.rs
lib/src/store.rs

#247 collection authorization

---

CHANGELOG.md
lib/defaults/default_store.json
lib/src/agents.rs
lib/src/collections.rs
lib/src/commit.rs
lib/src/db.rs
lib/src/hierarchy.rs
lib/src/plugins/invite.rs
lib/src/plugins/versioning.rs
lib/src/storelike.rs
server/src/commit_monitor.rs
server/src/handlers/search.rs

#247 exclude illegal members

---

CHANGELOG.md
Cargo.lock
README.md
lib/defaults/default_store.json
lib/src/hierarchy.rs
lib/src/urls.rs
server/Cargo.toml
server/README.md
server/openapi.yml
server/src/config.rs
server/src/handlers/download.rs
server/src/handlers/mod.rs
server/src/handlers/resource.rs
server/src/handlers/single_page_app.rs
server/src/handlers/upload.rs
server/src/helpers.rs
server/src/routes.rs

#72 file management

---

.github/workflows/release-github.yml
CHANGELOG.md
CONTRIBUTE.md
Cargo.lock
README.md
cli/README.md
lib/Cargo.toml
lib/README.md
lib/src/db.rs
server/Cargo.toml
server/README.md
server/src/appstate.rs
server/src/bin.rs
server/src/commit_monitor.rs
server/src/config.rs
server/src/content_types.rs
server/src/errors.rs
server/src/handlers/commit.rs
server/src/handlers/download.rs
server/src/handlers/resource.rs
server/src/handlers/search.rs
server/src/handlers/tpf.rs
server/src/handlers/web_sockets.rs
server/src/https.rs
server/src/process.rs
server/src/serve.rs
server/src/tray_icon.rs

#261 replace log with tracing

---

.gitignore
CHANGELOG.md
CONTRIBUTE.md
lib/src/commit.rs
lib/src/db.rs
lib/src/endpoints.rs
lib/src/plugins/files.rs
lib/src/plugins/mod.rs
lib/src/plugins/path.rs
lib/src/plugins/search.rs
lib/src/plugins/versioning.rs
pull_request_template.md
server/Cargo.toml
server/README.md
server/openapi.yml
server/src/commit_monitor.rs
server/src/config.rs
server/src/handlers/commit.rs
server/src/handlers/search.rs
server/src/handlers/web_sockets.rs
server/src/routes.rs

#259 endpoints

---

.github/workflows/release-github.yml
CHANGELOG.md
Cargo.lock
server/Cargo.toml
server/src/bin.rs
server/src/content_types.rs
server/src/handlers/download.rs
server/src/handlers/resource.rs
server/src/handlers/single_page_app.rs
server/src/handlers/tpf.rs
server/src/handlers/upload.rs
server/src/handlers/web_sockets.rs
server/src/helpers.rs
server/src/https.rs
server/src/routes.rs
server/src/serve.rs
server/src/tests.rs
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/README.md
src-tauri/src/main.rs

#246 update actix again

---

CHANGELOG.md
CONTRIBUTE.md
lib/src/db.rs

#282 refactor value index

---

CONTRIBUTE.md
Cargo.lock
lib/Cargo.toml
lib/benches/benchmarks.rs
lib/src/collections.rs
lib/src/db.rs
lib/src/db/query_index.rs
lib/src/db/test.rs
server/Cargo.toml

#293 Add Benchmarking

---

CHANGELOG.md
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/README.md
src-tauri/src/main.rs
src-tauri/src/menu.rs
src-tauri/src/system_tray.rs

#301 tauri upgrade to rc.2

---

CHANGELOG.md
lib/Cargo.toml
server/src/bin.rs
server/src/config.rs
server/src/handlers/commit.rs
server/src/handlers/download.rs
server/src/handlers/resource.rs
server/src/handlers/search.rs
server/src/handlers/single_page_app.rs
server/src/handlers/tpf.rs
server/src/handlers/upload.rs
server/src/handlers/web_sockets.rs
server/src/serve.rs
server/src/tests.rs

#303 no mutex for store in actix

---

CHANGELOG.md
lib/benches/benchmarks.rs
lib/src/hierarchy.rs

#307 allow reading commits

---

CHANGELOG.md
server/src/handlers/upload.rs

#366 remove std-async from upload

---

CHANGELOG.md
server/src/commit_monitor.rs

#345 get rid of unwraps in commit monitor

---

CHANGELOG.md
server/src/commit_monitor.rs
server/src/handlers/commit.rs
server/src/trace.rs

#413 index commits directly

---

lib/src/commit.rs

Now it's my time to be embarrassed 😬 
I introduced an error in #417: when `update_index == true`, `resource.get()` would try to get just removed property and would fail, resulting in changes not being saved.
Rework this part, so it gets property from unedited resource. And also handles the case when property does not exist by ignoring it—this works better then erroring out because current clients do not check for property existence before removing.
PR Checklist:

fix: fix updating index on commit.remove

---

CHANGELOG.md
lib/defaults/default_store.json
lib/src/agents.rs
lib/src/client.rs
lib/src/collections.rs
lib/src/commit.rs
lib/src/db/test.rs
lib/src/plugins/invite.rs
lib/src/populate.rs
lib/src/resources.rs
lib/src/storelike.rs
server/src/appstate.rs
server/src/handlers/upload.rs

#430 create agent does not depend on store

---

.dockerignore
.github/workflows/docker.yml
.gitignore
dockerfile

#436 minimal dockerfile

---

CONTRIBUTE.md
server/Cargo.toml

#453 actix version loosen

---

lib/defaults/default_store.json

#456 Add URI to default store

---

.github/workflows/main.yml
CHANGELOG.md
lib/src/plugins/bookmark.rs
lib/src/urls.rs
server/e2e_tests/package.json
server/e2e_tests/pnpm-lock.yaml

Extract image and description from webpage

---

CHANGELOG.md
lib/src/db.rs
lib/src/db/test.rs
lib/src/parse.rs
lib/src/store.rs
lib/src/storelike.rs
pull_request_template.md
server/src/search.rs

 #522 Return iterator from all_resources

---

dockerfile

#534 improve dockerfile port and volume documentation

---

.github/workflows/main.yml
.github/workflows/release-github.yml
CHANGELOG.md
lib/src/db.rs
lib/src/db/query_index.rs
lib/src/db/test.rs

#545 fix indexing logic

---

lib/src/db.rs

Fix grabby endpoint

---

CHANGELOG.md
lib/src/endpoints.rs
lib/src/plugins/mod.rs
lib/src/plugins/query.rs
lib/src/resources.rs
lib/src/storelike.rs
lib/src/urls.rs

Query endpoint

---

CONTRIBUTE.md

PR Checklist:
Pretty sure all above is not applicable to this PR. Just a few changes to the CONTRIBUTE.md file as I worked through setting up the project locally.

CONTRIBUTE.md updates

---

.github/workflows/main.yml
README.md
browser/data-browser/package.json
browser/package.json
browser/pnpm-lock.yaml
browser/svelte/.eslintrc.cjs
browser/svelte/.gitignore
browser/svelte/.prettierrc.json
browser/svelte/.trunk/.gitignore
browser/svelte/.trunk/configs/.markdownlint.yaml
browser/svelte/.trunk/trunk.yaml
browser/svelte/LICENSE
browser/svelte/README.md
browser/svelte/package.json
browser/svelte/pnpm-lock.yaml
browser/svelte/src/index.ts
browser/svelte/src/loadResourceTree.ts
browser/svelte/src/stores/getResource.test.ts
browser/svelte/src/stores/getResource.ts
browser/svelte/src/stores/getValue.test.ts
browser/svelte/src/stores/getValue.ts
browser/svelte/src/stores/store.ts
browser/svelte/src/vite-env.d.ts
browser/svelte/tsconfig.json
browser/svelte/vite.config.ts

@tomic/svelte move to monorepo

---

CHANGELOG.md
cli/tests/tests.rs
lib/defaults/default_store.json
server/src/appstate.rs

#706 search atomicdatadev

---

.vscode/tasks.json
Earthfile

Cross build

---

.earthlyignore
.gitignore
Cargo.lock
docs/src/atomicserver/installation.md
server/Cargo.toml
server/build.rs
server/src/handlers/single_page_app.rs

Build fix 689

---

.github/workflows/main.yml
.github/workflows/release.yml
Earthfile

Docker multiplatform

---

browser/CHANGELOG.md
browser/data-browser/src/components/ProgressBar.tsx
browser/data-browser/src/routes/History/HistoryRoute.tsx
browser/data-browser/src/routes/History/VersionButton.tsx
browser/data-browser/src/routes/History/useVersions.ts
browser/data-browser/src/routes/History/versionHelpers.ts
browser/lib/src/resource.ts
browser/pnpm-lock.yaml

 #745 Speedup resource history creation and provide feedback to user

---

browser/data-browser/src/components/ScrollArea.tsx
browser/data-browser/src/components/TableEditor/TableEditor.tsx

 #750 Show horizontal scrollbar on hover for tables

---

browser/CHANGELOG.md
browser/data-browser/src/views/TablePage/EditorCells/FloatCell.tsx
browser/data-browser/src/views/TablePage/EditorCells/IntegerCell.tsx
browser/data-browser/src/views/TablePage/helpers/formatNumber.ts

Tables number formatting respects user locale

---

CHANGELOG.md
Cargo.lock
lib/Cargo.toml
lib/src/commit.rs

Deterministic serialization JSON AD #794

---

browser/data-browser/src/components/AllProps.tsx
browser/data-browser/src/components/Main.tsx
browser/data-browser/src/components/PropVal.tsx
browser/data-browser/src/components/forms/ValueForm.tsx
browser/data-browser/src/helpers/containers.ts
browser/data-browser/src/views/TablePage/EditorCells/FloatCell.tsx
browser/data-browser/src/views/TablePage/PropertyForm/Inputs/DecimalPlacesInput.tsx
browser/data-browser/src/views/TablePage/helpers/formatNumber.ts

#762 data view page alignment

---

Earthfile
docs/src/atomicserver/installation.md

Improved docker rust cache

---

browser/CHANGELOG.md
browser/data-browser/src/components/forms/SearchBox/SearchBox.tsx

 #758 Fix Searchbox submitting forms

---

browser/CHANGELOG.md
browser/data-browser/package.json
browser/data-browser/src/components/InlineFormattedResourceList.tsx
browser/data-browser/src/components/Row.tsx
browser/data-browser/src/components/Tabs.tsx
browser/data-browser/src/components/Tag/CreateTagRow.tsx
browser/data-browser/src/components/Tag/Tag.tsx
browser/data-browser/src/components/Tag/index.ts
browser/data-browser/src/components/Tag/tagColours.ts
browser/data-browser/src/components/forms/AtomicSelectInput.tsx
browser/data-browser/src/components/forms/InputResourceArray.tsx
browser/data-browser/src/components/forms/SearchBox/SearchBoxWindow.tsx
browser/data-browser/src/views/OntologyPage/LabelText.tsx
browser/data-browser/src/views/OntologyPage/Property/EnumFormPart.tsx
browser/data-browser/src/views/OntologyPage/Property/PropertyCardWrite.tsx
browser/data-browser/src/views/OntologyPage/Property/PropertyFormCommon.tsx
browser/data-browser/src/views/OntologyPage/Property/filterAllowsOnly.ts
browser/data-browser/src/views/OntologyPage/Property/useEnumHandlers.ts
browser/data-browser/src/views/OntologyPage/PropertyDatatypePicker.tsx
browser/data-browser/src/views/OntologyPage/newClass.ts
browser/data-browser/src/views/ResourceInline/TagInline.tsx
browser/data-browser/src/views/TablePage/EditorCells/ResourceArrayCell.tsx
browser/data-browser/src/views/TablePage/PropertyForm/SelectPropertyForm.tsx
browser/e2e/tests/ontology.spec.ts
browser/pnpm-lock.yaml

#780 enums in ontologies

---

Earthfile

Cache mounts#805

---

browser/CHANGELOG.md
browser/data-browser/src/components/forms/InputNumber.tsx

 #819 Fix number input message

---

browser/CHANGELOG.md
browser/data-browser/src/components/Tag/CreateTagRow.tsx
browser/data-browser/src/views/TablePage/PropertyForm/PropertyForm.tsx

 #816 Fix table dialogs not submitting on enter

---

browser/data-browser/src/components/forms/BasicSelect.tsx
browser/data-browser/src/views/OntologyPage/Property/EnumFormPart.tsx
browser/data-browser/src/views/OntologyPage/Property/filterAllowsOnly.ts

#827-dont-set-allows-only-when-empty

---

browser/CHANGELOG.md
browser/data-browser/src/components/SideBar/usePanelList.ts
browser/data-browser/src/helpers/AppSettings.tsx
browser/data-browser/src/helpers/useDarkMode.tsx
browser/data-browser/src/hooks/useDriveHistory.ts
browser/data-browser/src/hooks/useLocalStorage.ts
browser/data-browser/src/views/CollectionPage.tsx
browser/data-browser/src/views/FolderPage/index.tsx
browser/data-browser/src/views/ResourcePage.tsx
browser/react/src/index.ts

 #825 Save displayStyle to localStorage

---

browser/CHANGELOG.md
browser/data-browser/src/components/TableEditor/ActiveCellIndicator.tsx
browser/lib/package.json
browser/lib/src/client.ts
browser/pnpm-lock.yaml

 #910 Remove Crossfetch and fix lexical scope for client.fetch

---

browser/CHANGELOG.md
browser/data-browser/src/components/Navigation.tsx
browser/data-browser/src/components/Parent.tsx
browser/data-browser/src/components/ResourceContextMenu/index.tsx
browser/data-browser/src/components/Searchbar.tsx
browser/data-browser/src/helpers/useFocus.tsx
browser/data-browser/src/routes/Share/ShareRoute.tsx
browser/e2e/tests/test-utils.ts

Redesign search bar to make it clear that it is a search bar. #936

---

browser/data-browser/src/views/CodeUsage/generators/CodeGenerator.ts

 #937 Fix invalid code generation for table columns
